// Generates the weekly 1-pager exec PDF for the JMR module.
// A separate full JMR PDF (one matrix per project) is generated by the
// existing /api/jmr/matrix-export/pdf route, called once per project.

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { getDashboardSnapshot } from './dashboard'
import { formatINRShort, formatDateIN } from './format'

export async function buildExecOnePagerPdf(): Promise<Uint8Array> {
  const snap = await getDashboardSnapshot()
  const doc = new jsPDF({ orientation: 'portrait', format: 'a4', unit: 'pt' })

  // Header band
  doc.setFillColor(29, 78, 216) // blue-700
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 56, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(15)
  doc.setFont('helvetica', 'bold')
  doc.text('CT HUB — Project Execution · JMR Weekly', 40, 26)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Snapshot: ${formatDateIN(new Date())}`, 40, 42)

  doc.setTextColor(17, 24, 39)

  // SPEND tile (single — Bills removed)
  let y = 84
  const w = doc.internal.pageSize.getWidth()
  doc.setFillColor(220, 252, 231)
  doc.roundedRect(40, y, w - 80, 64, 6, 6, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text('SPEND (JMR) — machinery + manpower · incl. GST', 52, y + 20)
  doc.setFontSize(20)
  doc.text(formatINRShort(snap.totals.spend), 52, y + 46)
  y += 88

  // Contractor table — logged spend
  autoTable(doc, {
    startY: y,
    head: [['Contractor', 'Logged spend']],
    body: snap.perContractor.slice(0, 12).map(c => [c.name, formatINRShort(c.spend)]),
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [243, 244, 246], textColor: [17, 24, 39] },
  })

  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(7)
  doc.setTextColor(120)
  doc.text(`Generated ${new Date().toISOString().slice(0, 16)} · CT HUB JMR`, 40, pageHeight - 24)

  return new Uint8Array(doc.output('arraybuffer'))
}

export function buildExecSummaryText(): string {
  // Used in WhatsApp pre-filled message + email body fallback.
  return [
    'CT HUB JMR — weekly snapshot',
    `Date: ${formatDateIN(new Date())}`,
    'PDFs attached: Exec 1-pager + Full JMR.',
    '',
    '— SRMD',
  ].join('\n')
}
